services:
  portfolio:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "1234:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.entrypoints=http"
      - "traefik.http.routers.portfolio.rule=Host(`sangeetsu.com`)"
      - "traefik.http.middlewares.portfolio-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portfolio.middlewares=portfolio-https-redirect"
      - "traefik.http.routers.portfolio-secure.entrypoints=https"
      - "traefik.http.routers.portfolio-secure.rule=Host(`sangeetsu.com`)"
      - "traefik.http.routers.portfolio-secure.tls=true"
      - "traefik.http.routers.portfolio-secure.service=portfolio"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true